# By using docker compose, both services (containers)
# are created on the same network and can therefore communicate.

# Restart: "no" , always, on-failure, unless-stopped
version: '3'
services:
  redis-server:
    image: 'redis'
  node-app :
    restart: always
    build: .
    ports:
     - "4001:8081" #for our local machine